### ISSUE TITLE
BUG: TestFilesRaceCondition.test_race_condition

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#980]
**Describe the bug**
In PR #966 one of the CI tests (Windows, Python 3.10) encountered this failure:

```
_________________ TestFilesRaceCondition.test_race_condition __________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\a\pysat\pysat\pysat\tests\test_files.py", line 1003, in create_instrument
    testInst = pysat.Instrument(inst_module=pysat.instruments.pysat_testing,
  File "D:\a\pysat\pysat\pysat\_instrument.py", line 482, in __init__
    self.files = pysat.Files(self, data_dir=self.data_dir,
  File "D:\a\pysat\pysat\pysat\_files.py", line 238, in __init__
    self.refresh()
  File "D:\a\pysat\pysat\pysat\_files.py", line 755, in refresh
    self._store()
  File "D:\a\pysat\pysat\pysat\_files.py", line 532, in _store
    stored_files = self._load(update_path=False)
  File "D:\a\pysat\pysat\pysat\_files.py", line 593, in _load
    loaded = pds.read_csv(fname, index_col=0, parse_dates=True,
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\io\parsers\readers.py", line 1231, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"""

The above exception was the direct cause of the following exception:

self = <pysat.tests.test_files.TestFilesRaceCondition object at 0x000001C299C4B1C0>

    def test_race_condition(self):
        """Test that multiple instances of pysat instrument creation run."""
        processes = 5
        proc_pool = Pool(processes)
        pysat.file_timeout = 1
    
>       proc_pool.map(create_instrument, range(processes))

pysat\tests\test_files.py:1102: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\multiprocessing\pool.py:364: in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.pool.MapResult object at 0x000001C299B6C190>
timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           pandas.errors.EmptyDataError: No columns to parse from file

C:\hostedtoolcache\windows\Python\3.10.1\x64\lib\multiprocessing\pool.py:771: EmptyDataError
---------------------------- Captured stdout setup ----------------------------
initial files created in  C:\Users\RUNNER~1\AppData\Local\Temp\tmpf_m7ylhd\pysat\testing\
```

**Expected behavior**
This test should pass

**Desktop (please complete the following information):**
 - OS: GitHub Actions Windows-latest
 - Version Python 3.10
 - Other details about your setup that could be relevant: numpy-latest

**Comment by jklenzing** [comment]
May be related to #871.

**Comment by jklenzing** [comment]
:window:

**Comment by jklenzing** [comment]
Stale issue
